import "dotenv/config";

const { 
     NODE_ENV,
     PORT, 
     TEST_DB_URL, 
     TEST_JWT_SECRET_KEY,
     TEST_REFRESH_SECRET,
     TEST_HOST,
     TEST_MAIL_USERNAME,
     TEST_MAIL_PASSWORD,
     TEST_OAUTH_CLIENTID,
     TEST_OAUTH_CLIENT_SECRET,
     TEST_OAUTH_REFRESH_TOKEN,
    } 
    = process.env;

export default {
    NODE_ENV,
    PORT,
    DB_URL: TEST_DB_URL,
    JWT_SECRET_KEY: TEST_JWT_SECRET_KEY,
    REFRESH_SECRET: TEST_REFRESH_SECRET,
    HOST: TEST_HOST,
    MAIL_USERNAME: TEST_MAIL_USERNAME,
    MAIL_PASSWORD: TEST_MAIL_PASSWORD,
    OAUTH_CLIENTID: TEST_OAUTH_CLIENTID,
    OAUTH_CLIENT_SECRET: TEST_OAUTH_CLIENT_SECRET,
    OAUTH_REFRESH_TOKEN: TEST_OAUTH_REFRESH_TOKEN,
};
